spring:
  application:
    name: knife4j-openapi3
  messages:
    basename: i18n/message
    encoding: utf-8
    cache-duration: 3600

server:
  port: 8083

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: desc
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
#  group-configs:
#    - group: 'default'
#      paths-to-match: '/**'
#      packages-to-scan: com.xiaominfo.knife4j.demo.web

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: en
  documents:
    - group: 分组1
      name: 文档1
      # 某一个文件夹下所有的.md文件
      locations: classpath:markdown/*
    - group: 分组2
      name: 文档2
      # 某一个文件夹下单个.md文件
      locations: classpath:markdown/doc1.md

